jenkins-x/jx-docs

content/_index.md

this excellent video by @rawlingsj deserves top billiing IMO

put in james excellent usage video

---

content/developing/create-quickstart.md

I thought it may make sense to point to where the quickstart repos are, as people may want to contribute some over time.
cc @jstrachan

some doc tweaks for quickstarts

---

Jenkinsfile

Ref. e.g. http://jenkins-x.io/getting-started/create-cluster/

Use last updated date from Git

---

content/troubleshooting/faq.md

made the below updates, rest atom seems to remove the line endings..
```
-Edit the file `~/.jenkins-x/cloud-environments/env-minikube/myvalues.yaml` and add the following content:
+Edit the file `~/.jx/cloud-environments/env-minikube/myvalues.yaml` and add the following content:
```

minor upadte for minikube path

---

config.toml
languages-switcher.html
nav-links-docs.html
site-nav.html

I put a multi-languages switch in the header of the page. The switch's style is not well. Maybe someone can help improve this later.
@jstrachan

 Add multi language menu switch

---

themes/gohugoioTheme/layouts/partials/nav-links-docs.html

It's my mistake, file nav-links-docs.html placed wrong way.
@jstrachan

fix Chinese menu can not be triggered

---

content/getting-started/create-cluster.md

s/minikube/minishift/ in the minishift section.

Fixed typo

---

content/getting-started/create-cluster.md

changed jx create cluster minikube     to       jx create cluster minishift

wrong command mentiond for Using Minishift (local)

---

themes/gohugoioTheme/layouts/partials/site-footer.html

Fixes mixed content warnings and re-establishes your street cred as masters of the crypto.

Use https profile.png now that https is working

---

content/getting-started/create-cluster.md

See https://github.com/jenkins-x/jx/issues/783 .

Make it clear that jx creates new cluster, not install Minikube

---

config.toml
content/developing/create-quickstart.zh.md
content/getting-started/install-on-cluster.zh.md
content/getting-started/install.zh.md

There is no command for Chinese for now, because of it\'s auto generated

fix broken links of command

---

content/developing/devpods.md

hey @jstrachan I felt like updating this with a more end-to-end feel to get people started - look ok?

clarifying and correcting devpods docs

---

content/getting-started/install-on-cluster.md

Commit 031932d inadvertently introduced some spurious characters
which broke formatting. Fixing it

install-on-cluster.md: Remove leading garbage

---

content/developing/preview.md
content/developing/security-features.md

I added some documentation imrovements that cover: 
* Security addon features
* Post preview hooks
please review @rawlingsj or @rajdavies

security and post preview job docs improvements

---

content/demos/talks.md

First four talks about Jenkins-X in German (more to come)

---

content/developing/import.md

Fix typo in 'import.md'

---

content/demos/talks.md

Please merge the new talk (+ fix for other talk)

Add/Fix talks: JUG KL on 2018/09/12 and Bed-Con 2018/09/06

---

content/architecture/custom-resources.md

I guess you meant to link [here](https://jenkins-x.io/about/features/#promotion)?

Broken link

---

content/getting-started/install-on-cluster-what-happens.md

Fix markdown links

---

Localization_Chinese.md

Update Chinese localization spec

---

content/getting-started/install-on-cluster-what-happens.md

The navigation between pages was broken as same weight on 2 pages. Also correct the `jx create aws` as too specific to aws.

Correct weight of page to ensure proper navigation order

---

content/getting-started/create-cluster.md

i stumbled a little following the getting started instructions for Minikube, the steps here should prove useful for anybody else looking to get started on their laptop. My testing was done from the master branch of jx (I built it from source and then used the binary at `/builds`).

Useful info for Minikube getting started: rationale for disk space, troubleshooting

---

content/demos/talks.md

Add my talks

---

CONTRIBUTING.md

Will review the content of the guide itself in a future PR even if already guide good

feat: Add basic contributing guide with link to website

---

content/demos/articles.md

Fixed link to 'JenkinsX – new Kubernetes dream? Part 2 - Technical'

Fixed link

---

content/getting-started/install-on-cluster.md

Added section Installing Jenkins X on IBM Cloud Private.

Add Installing Jenkins X on IBM Cloud Private

---

themes/gohugoioTheme/layouts/partials/languages-switcher.html
themes/gohugoioTheme/layouts/partials/site-nav.html

* change the link to current page
* hide menu when the page doesn't have translation

Multi-language menu improve

---

config.toml
content/security.md

chore(docs) document the security process

---

content/demos/talks.md

A few talks about Jenkins X /ok-to-test

Viktor Farcic - talks

---

content/demos/talks.md

This time a few upcoming talks and workshops. /ok-to-test /assign @rawlingsj

Viktor Farcic - future talks and workshops

---

README.md
content/developing/create-quickstart.md

add direct link to Hugo install page in README.md
fixes issue #1025

docs: fix path to buildpacks in quickstart

---

content/about/concepts.md

It looks like images were moved but concepts.md wasn't updated

Updated img source in concepts

---

content/demos/talks.md

I would like to add my video at the JDD Conference in Poland, where I promoted Jenkins X for the local community.

Adding video at JDD Poland

---

content/demos/talks.md

Google AppDev slides

---

content/demos/talks.md

- Add talk at gr8conf
- Re-order by date

Add talk at gr8conf + Re-order by date

---

content/about/concepts.md

found images that are not displayed because of wrong path

fix image links

---

content/contribute/apidocs.md
content/contribute/development.md

- also adding docs around tracing Kube API calls via TRACE_KUBE_API
fixes issue #1312

fix: updating docs around code generation

---

content/developing/serverless-apps.md

@jstrachan tested it out - and it works!
only issue I found was: https://github.com/jenkins-x/jx/issues/3632
And here are some doc tweaks. I am very jetlagged so hopefully it makes sense.

docs tidy up

---

content/getting-started/aws-terraform-install-gitops.md
content/getting-started/install-on-cluster.md

This is a short guide to setup EKS on AWS and the required resources for Jenkins X's setup of Vault
using Terraform. It assumes access to AWS is configured and familiarity with AWS and Terraform.

Create EKS cluster and vault requirements on AWS with terraform

---

LICENSE.md

https://github.com/jenkins-x/jx/issues/3398

Update license per issue #3398

---

content/contribute/apidocs.zh.md

add the missing apidocs page for zh_CN

i18n zh_CN apidocs page

---

content/developing/progress-delivery.md

cc @carlossg @rawlingsj I put a short blurb and link to carlos article on progressive delivery

progressive delivery article

---

themes/gohugoioTheme/layouts/_default/single.html

Fix styling so content doesn't overlap on larger screens

---

.gitignore
Dockerfile
charts/preview/.helmignore
charts/preview/Chart.yaml
charts/preview/Makefile
charts/preview/requirements.yaml
charts/preview/templates/_helpers.tpl
charts/preview/templates/deployment.yaml
charts/preview/templates/service.yaml
charts/preview/values.yaml
jenkins-x.yml

feat: add a preview chart

---

content/architecture/custom-jenkins.md

+ shell consistency in the code snippet to avoid UI differences between them
+ correct a broken link

 Typos in "Custom Jenkins" page

---

content/demos/talks.md

Signed-off-by: runzexia <runzexia@yunify.com>

kubecon 2019 china talks

---

content/getting-started/manage-via-gitops.md

The link should not point to a "localhost" URL.

Fix broken link for "jx_add_app"

---

content/developing/devpods.md

Just super quick fixes, nothing special :-)

Fix a couple broken links

---

content/getting-started/multi-cluster.md

Replacing Developmnet with Development

Update minor typo

---

content/commands/jx_controller_team.md
content/commands/jx_create_cluster_aks.md
content/commands/jx_create_cluster_aws.md
content/commands/jx_create_cluster_eks.md
content/commands/jx_create_cluster_gke.md
content/commands/jx_create_cluster_gke_terraform.md
content/commands/jx_create_cluster_iks.md
content/commands/jx_create_cluster_minikube.md
content/commands/jx_create_cluster_minishift.md
content/commands/jx_create_cluster_oke.md
content/commands/jx_create_codeship.md
content/commands/jx_create_terraform.md
content/commands/jx_install.md
content/commands/jx_step_bdd.md
content/getting-started/install-on-cluster.md

Drive-by: fix typo: organiation -> organization

Fix documentation link

---

content/architecture/docker-registry.md

added `generic` to the command

fixed last `kubectl create secret ...` command

---

content/architecture/pipeline-syntax-reference.md

This is still a work in progress - just wanted to throw up what I've got so far to make sure the structure looks reasonable to everyone.
fixes https://github.com/jenkins-x/jx/issues/4313
/assign @jstrachan 
/assign @wbrefvem 
cc @sharepointoscar

Add JX Pipeline syntax reference doc

---

content/architecture/pipeline-syntax-reference.md

Adding an example of defining a full pipeline in jenkins-x.yml

---

content/faq/issues.md

documenting a common cert-manager issue effecting kubernetes cluster v1.12 or older
relates to jenkins-x/jx/issues/3134

adding docs for cert-manager issue

---

content/architecture/dns.md

https://github.com/jenkins-x/jx/issues/4393

Adding information on external-dns

---

content/architecture/pod-templates.md

docs: Trivial update to documentation

---

content/getting-started/install.md

Signed-off-by: Cai Cooper <caicooper82@gmail.com>

fix: resolve issues in install documentation

---

content/architecture/dns.md

Signed-off-by: Cai Cooper <caicooper82@gmail.com>

chore: add more information regarding external-dns

---

content/commands/jx_create_cluster_gke.md

Better explanation of `--advanced-mode`

chore: update jx create cluster gke examples

---

content/developing/create-mlquickstart.md

Signed-off-by: Terry Cox <terry@bootstrap.je>

docs: Added machine-learning docs

---

content/architecture/pipeline-syntax-reference.md

Wait for https://github.com/jenkins-x/jx/pull/4748 to release before merging.
Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

chore: Add syntax reference for volumes

---

content/contribute/development.md

Fixes jenkins-x/jx#4951 and jenkins-x/jx#4952 

chore: document the checks we do on PRs

---

content/contribute/development.md

chore: describe how to handle DCO

---

themes/gohugoioTheme/layouts/partials/site-footer.html

Signed-off-by: Mark Cox <markcox20@hotmail.com>

fix: remove footer img text

---

content/contribute/pullrequestreview.md

chore: add PR review guide

---

content/contribute/development.md

fix: fixed typo in link to DCO image

---

content/contribute/contribute_dns.md

feat: add instructions for using DNS whilst developing

---

content/demos/articles.md
content/faq/setup.md

* add Jenkins X - Managing Jenkins
* add Jenkins X - Managing Nexus
* update previous links to use the [free friend Link from Medium](https://help.medium.com/hc/en-us/articles/360006543813-Friend-Links)

Add new articles, add Mediums friend link URLs

---

themes/gohugoioTheme/layouts/index.html

using relative links so that the links when running the site locally or in a Preview Environment work properly

fix: lets use relative links

---

content/architecture/lighthouse.md

and that its not really aimed yet at using jenkins servers

fix: a bit more clarity on lighthouse versus jenkins x pipelines

---

content/contribute/contribute_dns.md

fix: add a note linking to external dns page

---

content/getting-started/boot.md

add more detail around secrets/vault, ingress and webhooks

fix: polish boot docs

---

README.md
content/apps/_index.md
content/contribute/apidocs.md
content/contribute/apidocs.zh.md
content/news/changes-11-april-2018.md
content/news/changes-24-august-2018.md
local.Dockerfile
themes/gohugoioTheme/layouts/index.html

a few random link issues found by the link checker

Link fixes

---

content/commands/jx_create_cluster.md

update Azure Kubernetes Service name, azure container service has been deprecated

update Azure Kubernetes Service name

---

content/architecture/pod-templates.md

Fix broken url of `values.yaml` file in `jenkins-x-platform` repository.

docs: Fix broken url

---

content/architecture/tls.md

feat: add a section on TLS

---

content/en/_index.html

fix: making banner image dynamically resize

---

assets/scss/_variables_project.scss
content/en/_index.html

fix: sets theme-wide fonts

---

content/en/docs/managing-jx/common-tasks/install-on-cluster.md

fix: add alias for /docs/getting-started/install-on-cluster

---

layouts/partials/feedback.html

instead of sending helpful with a value of 0
fixes #1981

feat: send "unhelpful" event category when someone clicks unhelpful button

---

content/en/docs/contributing/documentation/_index.md

Add info on synching forks and creating branches

docs: edit contribution guide

---

content/en/docs/reference/components/docker-registry.md

without this, the command will fail

fix: Add missing equals sign

---

config.toml

chore: adding footer link for signing up to k8s slack

---

content/en/community/newsletter.md

Added new generic jenkins x newsletter form

added generic jenkins x newsletter subscription form

---

content/schemas/jx-requirements.json

a manual work around until the website updates properly with the version stream

fix: add json schema for jx-requirements.yml

---

content/en/docs/getting-started/setup/create-cluster/amazon/_index.md

Corrected spelling of "eksctl" from "elsctl".

fix: Typo. Misspelling of eksctl

---

content/zh/about/_index.md

Create the new About Jenkins X page in Chinese by translating English version.

chore: Translate about index page to Chinese

---

content/en/docs/getting-started/_index.md

Author: Chandani Kumari, Committer: Chandani Kumari <chandanikumari92@gmail.com>

fix : Modified path create-cluster to /docs/getting-started/setup/create-cluster

---

content/en/docs/contributing/documentation/_index.md

check: locally created changes. user.email set to GH 'private' user email.

docs: remove $ from shell command

---

content/en/docs/overview/accelerate.md

My guess is that the desired expression is "out of the box" and not "of the box". I'm not a native english speaker so if this is not the case just feel free to close this PR. Thanks!

fix: Adds missing word

---

content/en/docs/using-jx/faq/_index.md

This is based on my experimentations and understanding, please correct me if I'm wrong! ;)

chore: Add 'How do I inject Vault secrets...'

---

content/en/community/events/22-10-2019-anthos-jx.md

docs: update 22-10-2019-anthos-jx.md

---

content/en/docs/using-jx/faq/_index.md

Link to the promotion page changed in jenkins-x/jx-docs@9148fb42e7

fix: link to promotion page

---

content/en/docs/getting-started/first-project/create-quickstart.md

fix: Fix typo

---

content/en/docs/concepts/features.md

fix: fixed link syntax

---

content/en/docs/concepts/jenkins-x-pipelines.md

Clearer explanation. Wrong word. The right one is "included"

fix: Minor word choice change

---

google21d4dcad00285f05.html

to be able to use Google Event Data Highlighter
this is needed is part of #2133

chore: adding google site verification

---

content/en/docs/getting-started/promotion/_index.md

fix: correct helm cli.

---

content/en/docs/getting-started/setup/boot/how-it-works.md

docs: Fix link to parameters.tmpl.schema.json

---

content/es/docs/getting-started/setup/boot/_index.md

feat: Update repository section based on the english file.

---

content/es/docs/managing-jx/examples/_index.md

chore: Translate example page into Spanish.

---

content/en/docs/managing-jx/common-tasks/create-custom-builder.md

fix: page not found link.

---

content/en/docs/getting-started/_index.md
content/en/docs/getting-started/setup/boot/_index.md

- fixes #2143 link to deprecated docs
- includes a bunch of copy edits

docs: fix link to deprecated docs, make copy edits

---

.htmltest.yml
config.toml
content/es/docs/managing-jx/faq/_index.md
content/es/docs/managing-jx/faq/boot.md
content/es/docs/managing-jx/faq/issues.md
content/es/docs/reference/components/build-packs.md
content/es/docs/reference/components/cloud-native-jenkins.md
content/es/docs/reference/components/custom-resources.md
content/es/docs/reference/components/decisions.md
content/es/docs/reference/components/git.md
content/es/docs/reference/components/lighthouse.md
content/es/docs/reference/components/pod-templates.md
content/es/docs/reference/components/source.md
content/es/docs/reference/components/vault.md
content/es/docs/using-jx/creating/create-camel.md
content/es/docs/using-jx/creating/create-mlquickstart.md
content/es/docs/using-jx/creating/create-spring.md
content/es/docs/using-jx/creating/import.md
content/es/docs/using-jx/faq/_index.md
content/es/docs/using-jx/faq/chatops.md
content/es/docs/using-jx/faq/pipelines.md
content/zh/docs/using-jx/common-tasks/create-spring.md
jenkins-x.yml

Depends on:
relates to https://github.com/jenkins-x/jx/issues/5180

chore: add htmltest to pipeline

---

jenkins-x.yml

until we can fix the production site issues

fix: comment out htmltest in production pipeline for now

---

content/es/docs/getting-started/build-test-preview/_index.md

feat: Translate build-test-preview page into Spanish.

---

content/en/docs/reference/commands/jx_boot.md

Wrong url for more info on jx boot

fix: wrong url

---

content/en/community/office_hours/2019-04-19.md
content/en/docs/managing-jx/common-tasks/create-custom-builder.md
content/en/docs/managing-jx/common-tasks/storage.md
content/en/docs/managing-jx/tutorials/_index.md
content/en/docs/reference/devpods.md
content/en/docs/reference/multi-cluster.md

fixes #2242 #2246 #2245 #2243 #2244

fix: add aliases to capture old deep links that result in 404

---

content/en/_index.html
content/es/_index.html
content/zh/_index.html

Also copied updated landing page to translations

chore: Adding CloudBees CI-CD powered by Jenkins X to the sponsor section.

---

content/en/docs/getting-started/_index.md

have included a section for derived products and added a few headers to split up the content a bit

chore: updating the getting started landing page

---

content/en/docs/reference/components/vault.md

Added note on no supportability for existing Vault instance, though open issue exists and will be available sometime soon!

feat: Existing Vault Instance note

---

assets/scss/_variables_project.scss
layouts/partials/footer.html
layouts/partials/scripts.html

This is applying the changes raised here https://github.com/jenkins-x/jenkins-x-website/pull/17 and here https://github.com/jenkins-x/jenkins-x-website/pull/21

chore: adding LF footer + GA tracking

---

content/en/_index.html
content/es/_index.html
content/zh/_index.html

I forgot some `brew tap`  in https://github.com/jenkins-x/jx-docs/pull/2314. Here is the rest!
Sorry for the PR churn 😁

docs: brew, use one-liner where brew install does it all (2)

---

content/en/docs/using-jx/faq/_index.md

Correcting misspelling of microservice and adding question marks to questions missing them.

fix: Minimal typos and punctuation

---

content/en/blog/news/outreachy-blog1-2019.md

docs: Outreachy Blog1 - 2019 - Motivation to apply

---

content/en/docs/getting-started/_index.md
content/en/docs/getting-started/setup/create-cluster/google.md

hey @MarckK @sharepointoscar I added a link to oscars step by step, and mention CJXD as a "stable distro" (suggested by Ethan). 
Oscar may be working that into a guide, and I think @rawlingsj had some other ideas - but please take a look to see if it makes things clearer (also a typo with kubernetes in one spot). 
I think this all needs more work, both in CLI for UX but also docs to explain what is needed (I can't quite work out where), so if this gets in the way of that, please close it.

docs: small tweaks for install instructions

---

content/en/docs/getting-started/setup/boot/_index.md

Signed-off-by: Mark Cox <markcox20@hotmail.com>
#https://github.com/jenkins-x/jx/issues/6542

fix: upgrade schedule cron should contain 5 elements

---

content/en/docs/getting-started/setup/create-cluster/google.md

This docs change will add certain cluster requirements for Google clusters.

docs: add Google cluster requirements

---

content/en/_index.html

WIP -- for discussion on placement and wording
Note: the coloring of the inclosing boxes will be fixed, once placement finalised.
Wording needs to be finalised.
Should this talk be trimmed to just be Mo's talk -- this focuses squarely on benefits of Jenkins X. It's such a great summary of what JX offers. If we had visitors watch that 5-7 minutes segment that would be a huge win. I worry that having it too long loses people.

docs: add keynote to home page

---

content/en/docs/managing-jx/old/create-cluster.md

Fix is for Create Cluster docs.

fix: command to to download the jx binary

---

content/en/docs/getting-started/setup/boot/clouds/amazon.md

This PR addresses item 1 from https://github.com/jenkins-x/jx/issues/6732.

docs: Add EKS IAM permissions overview from CJXD

---

content/en/docs/getting-started/setup/boot/clouds/amazon.md

This PR addresses item 2 described in https://github.com/jenkins-x/jx/issues/6732.  Vault on EKS using Boot,

docs: Add Vault section to EKS boot document

---

content/en/docs/concepts/_index.md

Fixed spelling issues with book title.

fix: Update _index.md

---

content/en/docs/getting-started/setup/boot/clouds/amazon.md

Addresses item 3 from this issue - https://github.com/jenkins-x/jx/issues/6732.

docs: Add TLS and DNS instructions for booting to an EKS cluster

---

content/en/docs/managing-jx/common-tasks/create-custom-builder.md
content/en/docs/reference/components/pod-templates.md
content/es/docs/managing-jx/common-tasks/create-custom-builder.md
content/es/docs/reference/components/pod-templates.md
content/zh/docs/managing-jx/common-tasks/create-custom-builder.md
content/zh/docs/managing-jx/common-tasks/pod-templates.md

Edit's broken into 3 commits for each builder type

Updating various links pointing at older versions of builders

---

content/en/docs/concepts/components.md

Updated incorrect spelling for Jenkins.

fix: Update components.md

---

content/en/docs/reference/pipeline-syntax-reference.md

add stage promote to the list of stages

fix: Update pipeline-syntax-reference.md

---

content/en/docs/managing-jx/faq/issues.md

Describe how to remove a cluster with a certain name and then recreate it.

feat: Add section on recreating cluster with same name

---

content/en/docs/mlops/_index.md
content/en/docs/mlops/data.md
content/en/docs/mlops/gpu.md
content/en/docs/mlops/introduction.md
content/en/docs/mlops/mlquickstarting.md
content/en/docs/mlops/mlquickstarts.md

Signed-off-by: Terry Cox <terry@bootstrap.je>

feat: Added documentation for MLOps

---

content/en/docs/labs/boot/apps.md
content/en/docs/labs/boot/background.md
content/en/docs/labs/boot/benefits.md
content/en/docs/labs/boot/comparison.md
content/en/docs/labs/boot/how-it-works.md
content/en/docs/labs/boot/progressive-delivery.md

with Jenkins X with istio 1.5 / flagger / helm 3

fix: add a first spike at how to use progressive delivery

---

content/en/docs/_index.md

testing a PR against @jha-cloudbees branch 😃

chore: changing verbiage on getting started landing page

---

README.md
content/en/_index.html
content/en/blog/news/2020-fosdem-jx-talks.md
layouts/partials/search-input.html

fix: move docsy theme to lastest commit

---

Makefile
content/en/docs/contributing/_index.md
content/en/docs/contributing/code/_index.md
content/en/docs/contributing/documentation/_index.md
content/en/docs/contributing/documentation/apidocs.md
content/en/docs/contributing/documentation/changes.md
content/en/docs/contributing/documentation/reference.md
content/en/docs/contributing/documentation/step-by-step.md
content/en/docs/contributing/documentation/workflow.md
content/en/docs/contributing/sponsors.md

Content is pretty much still the same. I tried to update commands which were not correct anymore (used spell checker for example), but mainly I tried to break up the massive single page into more palatable smaller pieces.

chore: updating and restructuring the contributing to docs pages

---

content/en/docs/getting-started/setup/create-cluster/gke.md

fix: fixed typo in filename jx-requirements.yml

---

content/en/docs/getting-started/setup/create-cluster/_index.md

fix: updated typo and adjusted grammar on getting started pages - creating a cluster

fix: updated typo and adjusted grammar on getting started pages - creating a cluster

---

config.toml
content/en/_index.html
layouts/partials/footer.html

Re-arranged the homepage for better information flow, updating CTAs, fixing some color issues and fixing the footer on Safari.

fix: homepage revision

---

content/en/docs/guides/managing-jx/common-tasks/tls.md

Explains how to generate one certificate per Ingress

docs: Update tls.md

---

content/en/docs/getting-started/setup/_index.md

Adding the **Setup** section back on the left navigation to its original location.

chore: adding setup section to left nav

---

google834692bb5558ddf3.html

adding the google-provided html page that will let us authenticate the website with the google search console, to better control our SEO results.

chore: validating with google

---

assets/scss/_variables_project.scss

feat: increase header height to align logos

---

assets/scss/_variables_project.scss

fix: resolve navbar options on media view

---

google834692bb5558ddf3.html

Removing the Google Webmaster verification file as it is no longer needed.

chore: Removing google verification file

---

content/en/_index.html
static/css/style.css

*Before*:
*After*:
------Media view------
*Before* (google image causes page to overscale):
*After*:
-----Add sticky sidebar-----
*Before*:
*After*:

fix: resolve spacing in Docs section & make toc sidebar sticky

---

content/en/about/_index.md
content/zh/docs/getting-started/setup/boot/_index.md

Boot page was incorrectly redirecting to chinese translation.

fix: Updating boot redirect

---

content/en/community/_index.md
layouts/shortcodes/calendar.html
layouts/shortcodes/contributors.html
layouts/shortcodes/mailchimp.html

- added shortcode for creating list of contributors
- extracted mailchimp setup into shortcode
- extracted calendar into shortcode
- went to one line per sentence

chore: add list of contributors to community page

---

content/en/blog/news/may-2020-jxl-helm3-update.md

Adding the post to help the community understand what's next for JXL work.

docs: jxl and helm 3 blog post

---

content/en/community/code/_index.md

fix: bump version of go in the contribution guide

---

content/en/docs/resources/faq/issues.md

docs: add eks ingress section to faqs

---

content/en/docs/reference/multi-cluster.md

This is not a supported scenario as far as I know.

docs: unpublishing this page, as it refers to labs

---

content/en/docs/reference/components/lighthouse.md

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

chore: Update Prow/Lighthouse comparison

---

content/en/docs/install-setup/upgrade-jx.md

Fixes #2849
This PR documents the upgrade process using `jx upgrade boot`

chore: Update upgrade process

---

content/en/about/capabilities.md
content/en/docs/install-setup/installing/boot/clouds/_index.md

High level guidance across Kubernetes providers of what key jx features work and what do not
Signed-off-by: deanesmith <dsmith@cloudbees.com>

chore: Add capabilities matrix

---

content/en/docs/install-setup/installing/create-cluster/eks.md

fix: add missing sections to the eks terraform docs

---

content/en/about/capabilities.md
content/en/about/overview/changelog.md

Removed outdated support matrix.  Add bucket log storage to capabilities matrix.
Signed-off-by: deanesmith <dsmith@cloudbees.com>

chore: Remove outdated support matrix.

---

content/en/docs/create-project/build-packs.md

Describe how to setup custom buildpacks for clusters created with both boot & install.

docs: Add section about using custom buildpacks

---

content/en/_index.html
content/en/docs/_index.html
content/en/docs/install-setup/installing/install-binary/_index.md
content/en/docs/install-setup/upgrade-jx.md

refactor: replace deprecated version flag in the docs

---

content/en/docs/install-setup/installing/create-cluster/gke.md

docs: updating documentation for create cluster with GKE Terraform module

---

README.md

fix: fix documentation contribution link in readme

---

content/en/blog/news/2020-gsoc-story-of-zixuan.md

docs: gsoc blog post

---

content/en/docs/reference/components/docker-registry.md
content/en/docs/resources/guides/managing-jx/old/_index.md
content/en/docs/resources/guides/managing-jx/old/config.md

Superseding pull request #2619 and #2645.

fix: updating the Docker Repository configuration

---

content/en/community/roadmap.md

Adding the roadmap page  with links to placeholder issues. Will need to circle back and update links to all in progress work and tweak, but this should be a good first pass.

feat: roadmap page

---

content/en/docs/_index.html
content/en/docs/install-setup/create-cluster/eks.md
content/en/docs/install-setup/create-cluster/gke.md

docs: updating Terraform module usage for GKE and EKS

---

content/en/docs/install-setup/installing/boot/clouds/openshift.md

First draft of OpenShift documentation.

feat: first draft of OpenShift documentation

---

content/en/docs/install-setup/create-cluster/eks.md

fixes #2939 
Also adds a missing alert tag.

feat: add spot instance and  eks node group section

---

config.toml

fix: change feedback section link to point to jx-docs issue section

---

jenkins-x.yml

fix: change HUGO_VERSION to fix build issues

---

jenkins-x.yml

fix: attempt to fix master build

---

content/en/docs/install-setup/install-binary/_index.md

fix: change broken external link to an internal link

---

content/en/blog/news/2020-gsoc-consolidate-addons-and-apps-phase-2.md

Signed-off-by: Zixuan Liu <nodeces@gmail.com>
cc @MarckK

docs: add consolidate addons and apps coding phase 2 doc

---

content/en/docs/resources/faq/setup.md

Signed-off-by: David A. Urban <arpad9@gmail.com>
Fixes https://github.com/jenkins-x/jx-docs/issues/2998

docs: add help for stuck install

---

content/en/docs/resources/faq/setup.md

chore: add terraform debug information to faqs

---

content/en/docs/install-setup/create-cluster/eks.md

chore: add documentation around nat gateways and velero backups

---

content/en/community/_index.md

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

docs: add info on discourse

---

content/en/docs/install-setup/boot/_index.md
content/en/docs/resources/faq/setup.md

chore: add debugging information

---

content/en/community/roadmap.md

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

docs: update roadmap

---

content/en/docs/v3/guides/operator.md
content/en/docs/v3/guides/secrets/_index.md
content/en/docs/v3/guides/secrets/vault.md

fix: add better docs on git user token

---

content/en/docs/v3/guides/operator.md

fix: improve operator docs

---

content/en/_index.html

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

docs: edit buttons

---

content/en/docs/resources/guides/extending-jx/apps.md

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

docs: add official apps repository section

---

content/en/docs/resources/faq/using/_index.md

Signed-off-by: Kara de la Marck <MarckK@users.noreply.github.com>

docs: update FAQ on secrets management

---

content/en/docs/v3/getting-started/_index.md
content/en/docs/v3/getting-started/eks.md
content/en/docs/v3/getting-started/gke.md

feat: docs for running jx3 on eks

---

assets/scss/_sidebar-tree.scss
layouts/partials/navbar.html
static/css/style.css

fix: fix docs navbar to top

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Fixes https://github.com/jenkins-x/jx-docs/issues/3037

fix: creation of Issue Templates for users reference

---

content/en/docs/resources/faq/setup.md

fix: add a faq around issues with terraform destroy

---

content/en/docs/build-test-preview/preview.md

I guess I could be wrong, but this is what I understand.

preview environment creation details are incorrect

---

layouts/partials/navbar.html
layouts/partials/scripts.html
layouts/partials/toggle.html

feat: add dark mode to jx-docs website

---

config.toml
content/en/docs/_index.html
layouts/partials/head-css.html
layouts/partials/scripts.html
static/css/prism.css

Resolves #3049 
Signed-off-by: borntorock <borntorock@users.noreply.github.com>

feat: prism support for syntax highlighting and copy button on code blocks

---

content/en/blog/news/2020-pipelines-visualizer.md

@MarckK @rawlingsj @jstrachan what do you think?

docs: add blog post for the jx-pipelines-visualizer

---

content/en/blog/news/2020-pipelines-visualizer.md

related to https://github.com/jenkins-x/jx-docs/pull/3073

fix(blog): fix the size of the embedded youtube video

---

content/en/docs/v3/about/changes.md
content/en/docs/v3/guides/faq/_index.md
content/en/docs/v3/guides/pipeline-catalog.md
content/en/docs/v3/guides/upgrade.md

fix: first spike at changes doc

---

content/en/docs/v3/guides/upgrade.md

and add detail on how to revert version stream changes

fix: improve upgrade docs

---

content/en/docs/v3/getting-started/eks.md

refactor: change the quickstart repo for eks

---

content/en/docs/v3/guides/infra/_index.md
content/en/docs/v3/guides/operator.md

to avoid confusion and link to the main admin getting started pages

fix: polish the infra guides page

---

.github/PULL_REQUEST_TEMPLATE.md

Partial fixes https://github.com/jenkins-x/jx-docs/issues/3116
This PR includes the github Pull Request template as reference for the PR submitters.

feat: added PR template for submitters

---

content/en/v3/admin/guides/infra/tls_dns.md

docs: FaQ on avoiding namespaceSubdomain

---

.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml

chore: more pipeline fixes

---

assets/scss/_sidebar-tree.scss

This is a hacky way to solve #3072 for now. Merging this PR wont close that issue, we should figure out a clean way to make it work.
Related to #3072

fix(sidebar): remove sidebar searchbox

---

content/en/v3/about/_index.md

so the first page has the nice icons ;)

fix: add the develop+admin cards to the docs

---

content/en/v3/develop/create-project/_index.md

This is just a minor change to the wordings on importing an existing project to jenkinsX.

chore: minor edit to create project docs

---

content/en/_index.html

This PR changes the landing page links to the new v3 section of the docs.

refactor: minor edits to the landing page

---

content/en/about/_index.md

Correct misspelling of "principles"

docs: Update _index.md

---

content/en/v3/admin/guides/upgrade.md

docs: add docs on how to track teh upgrade from a boot job

---

.lighthouse/jenkins-x/preview.yaml
content/en/blog/news/2020-jx-v3-update.md

chore: project update for jx3 next steps moving out of alpha

---

content/en/v3/about/changes.md

which require a little bit of work to upgrade

fix: first spike at the pre-beta changes

---

.lighthouse/jenkins-x/release.yaml

chore: no need to publish changelog for the website

---

.lighthouse/jenkins-x/preview.yaml
content/en/v3/admin/guides/tls_dns.md
content/en/v3/admin/guides/upgrades/_index.md
content/en/v3/admin/guides/upgrades/cli.md
content/en/v3/admin/guides/upgrades/cluster.md
content/en/v3/admin/guides/upgrades/infrastructure.md
content/en/v3/admin/guides/upgrades/lts.md

docs: move upgrade into a tree and add docs on LTS

---

content/en/v3/admin/troubleshooting/_index.md
content/en/v3/admin/troubleshooting/webhooks.md
content/en/v3/develop/faq/_index.md

fix: lets add a troubleshooting section

---

content/en/_index.html
content/en/about/_index.md
content/en/v3/about/_index.md
content/en/v3/develop/faq/_index.md

fix: polish links

---

.lighthouse/jenkins-x/triggers.yaml

fix: pipeline, re-run not needed

---

content/en/v3/admin/guides/tls_dns.md

chore: tidy up tls docs

---

content/en/blog/news/2021-jx3-walkthroughs.md

docs: v3 walkthrough blog

---

content/zh/v3/develop/create-project/_index.md

docs: Add Chinese document of create project

---

content/en/v3/about/overview/_index.md
content/en/v3/develop/faq/_index.md

fix: add FAQ on using GPUs

---

content/en/blog/news/2021-jx3-feb-lts.md

docs: feb 21 lts

---

content/en/blog/news/2021-jx3-feb-lts.md

chore: tidy grammer

---

content/en/v3/admin/guides/jenkins/example.md

docs: Typo corrections

---

content/en/v3/admin/setup/config/repository.md

Complete this page with informations from https://jenkins-x.io/v3/develop/faq/config/registries/#how-do-i-switch-to-github-pages-for-charts

fix: complete bucketrepo

---

content/en/v3/develop/pipelines/inner-loop/_index.md
content/en/v3/develop/pipelines/inner-loop/localizer.md

thanks @hervelemeur for the link

fix: add article and localizer docs

---

content/en/v3/admin/guides/multi-cluster/multi-cluster-example.md

Update the multi-cluster-example.md document to include additional environment tuning  steps

docs: enhance multi-cluster-example.md

---

content/en/v3/admin/guides/observability/_index.md
content/en/v3/admin/guides/preview-environments/_index.md
content/en/v3/develop/environments/preview.md

explains how to install/use https://github.com/dailymotion-oss/osiris to scale preview environments
(scale them down/up automatically)

chore: add an admin guide to install osiris for preview envs

---

content/en/v3/about/comparison.md
content/en/v3/about/overview/_index.md
content/en/v3/about/what.md
content/en/v3/develop/environments/promotion.md

docs: lets tidy up the what is Jenkins X from a renewed view of v3

---

content/en/blog/news/2021-jx3-builtin-observability.md

note that it should be merged after https://github.com/jenkins-x/jx-docs/pull/3282
(it re-uses some images from this PR)

docs: new blog post for the built-in observability

---

content/en/blog/news/2021-jx3-osiris-preview-envs.md
content/en/v3/admin/guides/preview-environments/_index.md

promote the integration of osiris, to automatically scale down/up the preview envs

docs: new blog post for scaling preview envs with osiris

---

content/en/v3/about/changes.md
content/en/v3/about/extending.md
content/en/v3/about/overview/source.md
content/en/v3/admin/setup/jx3/_index.md
content/en/v3/admin/setup/upgrades/cli.md
content/en/v3/develop/reference/jx-help.md
content/en/v3/develop/reference/jx/_index.md
content/en/v3/develop/reference/variables.md
content/en/v3/develop/ui/cli.md

and add notes on getting CLI help

fix: add jx CLI links

---

content/en/v3/develop/ui/dashboard.md

to include screenshots and explain how to get the pipeline trace

docs: update jx-pipelines-visualizer doc

---

content/en/v3/develop/developing/_index.md
layouts/shortcodes/developcards.html

fix: lets move the developer guide more centrally

---

content/en/blog/news/2021-jx3-apr-lts.md

docs: April LTS release

---

layouts/partials/page-meta-links.html

as we've moved the default branch

fix: edit this page links

---

content/en/v3/develop/create-project/jenkinsfile.md

Correct spelling of "Jenkinsfile".

fix: Update jenkinsfile.md

---

content/en/v3/admin/platforms/azure/_index.md
content/en/v3/admin/platforms/eks/_index.md
content/en/v3/admin/platforms/google/_index.md
content/en/v3/admin/platforms/minikube/_index.md
content/en/v3/admin/platforms/on-premise/_index.md
content/en/v3/admin/platforms/openshift/_index.md
content/en/v3/admin/platforms/openshift/openshift-crc.md

fix: make it clear to use https cloning

---

.gitpod.Dockerfile
.gitpod.yml
README.md

chore: add gitpod config for users easy to do contribution

---

README.md
content/zh/v3/admin/_index.md
content/zh/v3/admin/troubleshooting/_index.md
content/zh/v3/admin/troubleshooting/webhooks.md

docs: add Chinese doc for v3 admin troubleshooting

---

content/en/v3/develop/ui/slack.md

New users may not know the different values, so having it in the docs will help them.

chore: add some extra information about kind and filter values for new users

---

content/en/v3/develop/faq/config/charts.md

fix: add better FAQ on env config

---

content/en/v3/mlops/_index.md
content/en/v3/mlops/data.md
content/en/v3/mlops/gpu.md
content/en/v3/mlops/introduction.md
content/en/v3/mlops/mlquickstarting.md
content/en/v3/mlops/mlquickstarts.md

Signed-off-by: Terry Cox <terry@bootstrap.je>
Added a new set of documentation for MLOps with Jenkins-X v3.

docs: Added MLOps docs for v3

---

layouts/partials/breadcrumb.html

an attempt at Ankit's fix using a simpler template

fix: add v2 warning

---

content/en/community/_index.md

chore: Link to https

---

content/en/v3/about/overview/_index.md

chore: corrected typo on index.md

---

content/en/blog/news/2021-cdcon.md
content/en/v3/develop/apps/_index.md
content/en/v3/develop/faq/config/charts.md

* add FAQ on adding a db
* add Kara's talk at GitOps summit

fix: improve the customizing charts docs

---

content/en/v3/admin/guides/lighthouse-webui/_index.md

fix: typo in the lighthouse webui install guide

---

static/css/style.css

_Signed-off-by: amino19  <anshumaankrprasad76@gmail.com>_
Commit update the site to be "mobile-friendly"
Fixes #3313  (issue)

fix: [Docs/Bug] Mobile view updated

---

content/en/blog/news/2021-argo.md

so that images are auto-upgraded

fix: reuse the updatebot task

---

content/en/v3/develop/ui/cli.md

Signed-off-by: shaowenchen <mail@chenshaowen.com>
fix broken link

fix: broken link

---

content/en/v3/about/changes.md

fix: add upgrade job workaround

---

content/en/community/_index.md

fix: use correct time for office hours

---

content/en/v3/about/extending.md

chore: add docs for updatebot with custom pipeline catalogs

---

content/en/v3/develop/environments/promotion/_index.md

docs: fix 1 typo in the md file

Fixed typos

---

config.toml

chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.12

---

config.toml

chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.13

---

content/en/v3/develop/faq/issues.md

fix: add FAQ on upgrade cli

---

config.toml

chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.14

---

config.toml

chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.15

---

content/en/v3/admin/setup/config/repository.md
content/en/v3/develop/pipelines/catalog.md
content/en/v3/develop/ui/lens.md

add docs for github or custom maven repo
add docs on override step properties locally
polish Lens install instructions

fix: add docs for custom git repositories

---

config.toml

chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.16

---

content/en/blog/news/2021-gitops-secrets.md
content/en/v3/admin/setup/config/repository.md

fix: add blog on gitops and secrets

---

content/en/blog/news/2021-moving-v2-infra.md

docs: add extra details for migrating v2 installs to GH

---

content/en/blog/news/2021-moving-v2-infra.md

chore: upadte more v2 docs when migrating to github

---

content/en/blog/news/2021-moving-v2-infra.md

fixed the docker image tag.

---

content/en/blog/news/2021-moving-v2-infra.md

chore: use correct command

---

content/en/blog/news/2021-moving-v2-infra.md

Expand override needed to replace gcr.io images with ghcr.io ones

---

content/en/blog/news/2021-moving-v2-infra.md

chore: more v2 GitHub migration edge case steps

---

content/en/blog/news/2021-moving-v2-infra.md

chore: use correct tag

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
content/en/blog/news/2021-moving-v2-infra.md

fix: update list for builder image on app repos

---

content/en/v3/admin/guides/multi-cluster/multi-cluster-example.md

- updating `jx3/` paths to `jxgh/`
- adding note to OSX users about `sed -i`
- replacing ‘master’ branch ref with ‘main’
- ‘bucketrepo’ chart no longer included in default setup, deleted removal instructions
- resolves #3450

chore: updating multi-cluster-example chart paths

---

content/en/v3/about/what.md

fix: Update what.md

---

content/en/v3/about/changes.md

fix: minor spelling error fixed

---

content/en/v3/admin/platforms/eks/_index.md
content/en/v3/admin/setup/secrets/vault.md

feat: add documentation around external vault

---

content/en/blog/news/2021-hacktoberfest.md

Short blog on hacktoberfest 2021.

feat: add a short blog on hacktoberfest 2021

---

content/en/v3/develop/faq/issues.md

Signed-off-by: thevinter <theniki98@gmail.com>
Added additional information for debugging a 500 error in chartmuseum during the promote step.
- [x ] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ x] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ x] Any dependent changes have already been merged.

fix: improved chartmuseum 500 error FAQ

---

content/en/blog/news/2021-hacktoberfest-conclusion.md

refactor: blog on hacktoberfest 2021 conclusion

---

content/en/v3/admin/guides/_index.md
content/en/v3/admin/setup/_index.md
content/en/v3/admin/troubleshooting/_index.md
content/en/v3/admin/uninstall/_index.md
content/en/v3/admin/uninstall/delete-jx-cluster.md
content/en/v3/admin/uninstall/delete-jx.md

It was not clear on how to uninstall/remove Jenkins X.
This PR fixes that.

refactor: clear instructions on how to uninstall jx

---

content/en/v3/admin/platforms/eks/_index.md
content/en/v3/admin/setup/secrets/vault.md

There is no need to modify the makefile in the version stream.

fix: update docs now that external vault support is stable

---

content/en/v3/admin/setup/secrets/vault.md

refactor: add more information about boot secrets

---

content/en/v3/admin/troubleshooting/bot-token.md
content/en/v3/admin/troubleshooting/install.md
content/en/v3/admin/troubleshooting/secrets.md
content/en/v3/admin/troubleshooting/webhooks.md

Add some troubleshooting tips arounfd installation.

fix: add some troubleshooting information around installation

---

content/en/v3/develop/create-project/_index.md

We recently added support for nested gitlab repositories in Jenkins X v3, documenting it in this PR.

fix: add a note on gitlab nested repositories

---

content/en/v3/admin/platforms/k3s/_index.md

Add a note about installing vault cli before starting vault docker container.

fix: add a note about installing vault cli

---

content/en/blog/news/2021-kaniko-azure-resolution.md
content/en/v3/admin/platforms/azure/_index.md

Adds a blog about the issues we've seen with kaniko and some resolution steps
Fixes https://github.com/jenkins-x/jx/issues/8029

chore: added new blog post for issues with azure

---

content/en/v3/admin/platforms/k3s/_index.md

fix: add a note about jq installation and k8s 1.22 support

---

content/en/v3/admin/troubleshooting/install.md
content/en/v3/admin/troubleshooting/quickstart-import.md

Some troubleshooting tips around import and quickstart.

feat: add troubleshooting guide around import and quickstart

---

content/en/v3/admin/guides/spot-instances/_index.md

Added some documentation for using spot instances to build with Tekton
Waiting for AWS instructions

feat: added spot instances for building documentation

---

content/en/community/_index.md
content/en/community/calendar.md
content/en/community/office_hours/_index.md
layouts/shortcodes/calendar.html

refactor: add new links for office hours

---

content/en/community/_index.md

fix: change office hours to 1500 UTC

---

content/en/v3/admin/setup/config/repository.md

Added some info on the necessary permissions for using github as maven

docs: added note on github maven permissions

---

layouts/shortcodes/calendar.html

fix: Display calendar in UTC

---

content/en/v3/admin/platforms/k3s/_index.md

changed the k3s install command to fix permission errors
added troubleshooting step for vault auth
added troubleshooting step for k3s cluster connection

docs: Updated k3s install command/ Vault Troubleshooting steps

---

content/en/blog/news/2022-survey.md
layouts/partials/breadcrumb.html

Added a blog post with info on the Jenkins X survey, and edited the breadcrumb to include a very visible link on all documentation pages for v3.

New blog post about the Jenkins X survey

---

content/en/v3/develop/_index.md
content/en/v3/learning-resources/_index.md

Linux foundation has an updated course on Jenkins X v3.

feat: add link to linux foundation course on jx

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
docker-compose.yml

refactor: upgrade hugo docker image to 0.91.2

---

layouts/partials/breadcrumb.html

Survey is over, removing the banner.

chore: remove survey banner

---

content/en/_index.html

refactor: add id to jx users section

---

content/en/_index.html

fix: add users id to the right section

---

content/en/_index.html
layouts/partials/navbar.html
package-lock.json

Fixing the overlapping of heading in mobile view.
Fixes # (issue) 
#3522

Fix: top-padding in tag-line

---

content/en/blog/news/jx-202201.md

Updates from Jenkins X for the month of January, 2022!

feat: January updates from Jenkins X

---

content/en/blog/news/2022-survey.md
layouts/partials/breadcrumb.html

Extended period of survey to February 11

docs: extended survey period

---

content/en/blog/news/jx-202201.md

fix: add missing contributor to january blog post

---

config.toml
layouts/partials/footer.html

Changes the alignment of footer items, also looks better on mobile view, also added some more social links.
#3535

fix: alignment of text & adding new links

---

content/en/blog/news/2022-gsoc.md

Project ideas for Google Summer of code (GSoC) 2022

feat: add a blog with project ideas for gsoc 2022

---

content/en/blog/news/2022-gsoc.md

Add a difficulty rating to gsoc project idea.

chore: add difficulty rating to gsoc project ideas

---

content/en/v3/develop/faq/config/secrets.md

fix: mention running port forward when editing secret in vault

---

content/en/v3/admin/platforms/on-premises/_index.md

Signed-off-by: Stephen Morgan <steve@rebelops.io>
Two links were broken, removed them to clean up docs. 
Fixes # #3551 
- [ x] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ x] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [x ] Any dependent changes have already been merged.

fix: removed non-working links from docs

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
docker-compose.yml

Updates to hugo docker image and docsy submodule

chore: update hugo image and doscy submodule

---

content/en/blog/news/2022-gsoc-followup.md
content/en/blog/news/2022-gsoc.md

We got accepted into GSoC, this is the follow up blog promised!

feat: add a gsoc 2022 follow up blog

---

config.toml
content/en/blog/news/2022-gsoc-followup.md
content/en/v3/admin/platforms/k3s/_index.md
layouts/partials/breadcrumb.html

Make it even more clear that v2 is not maintained and should not be used.

refactor: make it more clear that v2 is not maintained

---

.gitmodules
config.toml
go.mod
go.sum

Signed-off-by: Aabhas Sao <aabhassao0@gmail.com>
Added docsy theme as a go module and removed docsy as git submodules.
Fixes #3516

feat: switch to docsy go module

---

content/en/blog/news/2022-gsod.md

List of ideas for Google summer of docs 2022!

fix: add gsod blog

---

content/en/blog/news/2022-gsod.md

fix: add gsod proposal and budget

---

content/en/community/_index.md

We now have a cdf zoom account for Jenkins X

feat: add new zoom link from cdf jx account

---

Makefile
README.md
README_CN.md

update the readme and translate to CN
Fixes #3579

docs: update readme and add CN-README

---

content/en/blog/news/2022-gsoc-followup.md
content/en/blog/news/2022-gsoc-project-template.md
content/en/blog/news/2022-gsoc.md

Proposal template for Google Summer of Code contributors

feat: project proposal template for GSOC

---

content/en/blog/news/2022-gsoc-followup.md
content/en/blog/news/2022-gsoc-project-template.md

fix: minor cleanup of project template

---

content/en/v3/admin/setup/jx3/_index.md

fix: jx cli install -  remove the top line about "beta jx" version

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
Makefile
docker-compose.yml

Upgrade Hugo to 0.95.0
Passing local build. Tested build with both commands make server and make compose-up.

chore: update Hugo to 0.95.0

---

content/en/community/code/_index.md

Updating the contribution guide by adding how to find jx repos, a linting section, loading dependencies before changing code, ask a maintainer to be your PR reviewer
Fixes #3583

docs: updating contribution guide

---

content/en/blog/news/2022-04-22-k8s-122-tekton.md
content/en/v3/admin/platforms/k3s/_index.md

docs: k8s 1.22 and tekton breaking change

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml

Remove resource requests in step template, so now pods can be scheduled on nodes.

fix: remove resource request from step template

---

content/en/blog/news/2022-04-22-k8s-122-tekton.md

Corrected the URL for Tekton LimitRange support in Pipeline documentation
Updated a document URL reference

doc: Tekton LimitRange URL

---

content/en/v3/about/what.md

Just a small typo fix that I found while reading the docs

Typo fix "pakages"

---

content/en/v3/develop/faq/config/charts.md

Fix minor typos in local chart installation.

fix: minor typo in local chart installation instructions

---

content/en/v3/admin/platforms/k3s/_index.md

feat: add instructions to install vault operator and vault instance chart in k3s

---

content/en/v3/admin/guides/jenkins/example.md

Updated the steps to build Jenkins server based  upon current system level settings.

Upgrade Jenkins Server Example page

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
Makefile
config.toml
docker-compose.yml
go.mod
go.sum
layouts/partials/breadcrumb.html

Upgrading hugo and docsy to the latest version

fix: upgrade docsy and hugo

---

content/en/v3/about/concepts/_index.md
content/en/v3/about/concepts/deployment-lifecycle.md
content/en/v3/about/concepts/environments.md
content/en/v3/about/concepts/pipeline-activity.md
content/en/v3/about/concepts/source-repository.md

First pass at adding documentation for jx concepts.
Does not talk about lot of things, but it's a start.
We can add more things subsequently.
This is also part of the 30 day plan for the GSoC interns.

feat: add docs around jx concepts

---

content/en/community/maintainer_guide/_index.md
content/en/community/maintainer_guide/go-upgrades.md
content/en/community/maintainer_guide/infrastructure.md
content/en/community/maintainer_guide/mentorship/_index.md
content/en/community/maintainer_guide/mentorship/gsoc.md

We dont have a maintainer guide, this is an attempt at adding one.
Hopefully, we will make it better with time.

feat: add a maintainer guide for jenkins x

---

content/en/community/security.md

use jx-admin email for security incident reporting

fix: security incidence report

---

content/en/v3/admin/guides/k8s-upgrades/_index.md

Fixes issue https://github.com/jenkins-x/jx/issues/8305 

docs: added k8s upgrade guide

---

content/en/community/maintainer_guide/go-upgrades.md

More information to streamline the go upgrade process

fix: add information around catalog and version to go upgrade guide

---

layouts/_default/sitemap.xml
layouts/partials/head.html
layouts/partials/page-description.html
layouts/robots.txt

Adds meta tags to disallow google indexing of all pages under /docs folder
Takes all the same pages out of sitemap.xml

fix: remove /docs

---

config.toml

chore(deps): upgrade jenkins-x/jx-docs.git to version 1.0.18

---

.github/actions/create-pr-for-plugin-docs/action.yaml
.github/workflows/regenerate.yml
regen-plugins.sh

fix: Link to run

---

content/en/community/maintainer_guide/supply-chain-security.md

Documentation for steps in https://github.com/jenkins-x/jx/issues/8348

docs: add support for supply chain security

---

content/en/blog/news/2022-hacktoberfest.md

chore: blog for hacktoberfest 2022

---

assets/scss/_code.scss
layouts/partials/scripts.html

Signed-off-by: Anudeep Ghosh <91572535+anudeep-bpgc@users.noreply.github.com>
This PR adds the feature requested under the issue id #3089 for allowing users to enlarge images by clicking on them
in the documentation.
Dependencies include usage of JavaScript library called ['medium-zoom'](https://www.npmjs.com/package/medium-zoom)
[/layouts/partials/scripts.html](https://github.com/jenkins-x/jx-docs/blob/main/layouts/partials/scripts.html)
added medium-zoom JavaScript library source from CDN
added JavaScript code using HTML Element selector to select images from documentation and add the zoom-in functionality
[/assets/scss/_code.scss](https://github.com/jenkins-x/jx-docs/blob/main/assets/scss/_code.scss)
added code to keep the zoomed-in image above nav-bar

feat: add feature to enlarge image on click

---

content/en/blog/news/2022-GSoC-2022-Supply-Chain-Security-Final-Report.md

This is a Blog Post (or a report) summarizing all my work during the GSoC period on Supply Chain Security with Jenkins-X

docs: GSoC report

---

content/en/v3/admin/platforms/minikube/_index.md

fix: add info on the procedure when  restarting minikube session

---

content/en/v3/admin/platforms/k3s/_index.md
content/en/v3/develop/faq/ngrok.md

fix: modify k3s docs

---

content/en/v3/admin/platforms/azure/_index.md

fix: remove kaniko alert

---

content/en/v3/about/what.md

Fixed minor type in the what.md docs that are displayed in https://jenkins-x.io/v3/about/what/

fix: Fix typo in what.md docs

---

layouts/shortcodes/k8s-versions.html

Updating the versions of K8s supported by JX

chore: update supported k8s versions

---

content/en/v3/admin/setup/secrets/_index.md

jx secret import does not exist, but on the other hand jx secret vault shell is worth mentioning

fix: correct vault commands

---

content/en/v3/develop/apps/_index.md

Helmfile has moved. I've updated the URLs.

Helmfile has moved.

---

content/en/v3/develop/environments/config.md
content/en/v3/develop/environments/promotion/_index.md

Some improvements in the documentation regarding promotion.

docs: improve promote documentation

---

content/en/blog/news/2024-migrating-artifact-registry.md
content/en/v3/develop/faq/config/registries.md

Adding pointers to documentation regarding migration to artifact registry
Fixes jenkins-x/jx#8656

docs: migrating to artifact registry

---

content/en/v3/admin/platforms/eks/_index.md

related to jenkins-x/terraform-aws-eks-jx#377

docs: update after refactored eks terraform modules

---

config.toml
content/en/_index.html

Removing all references to twitter. Our twitter (X) account is apparently deleted.
Fixes jenkins-x/jx#8637

docs: remove references to twitter

---

content/en/community/roadmap.md

docs: roadmap

---

.lighthouse/jenkins-x/preview.yaml
content/en/v3/develop/environments/config.md

docs: fix broken formatting
