jenkins-x/jx-docs

content/commands/jx_create_quickstart.md

The command docs there were copy pasted from maven it looks like, which is confusing. I think better to leave it mostly empty until we get to flesh it out (brand new feature)

Edit create quickstart command docs

---

themes/gohugoioTheme/layouts/partials/nav-links-docs.html

See my another pr [Fix problem where non-ASCI menu links cannot be triggered](https://github.com/gohugoio/gohugoioTheme/pull/88).

Use menu item's identifier instead of name

---

content/getting-started/install-on-cluster.md

With fewer than this number of spare vCpus Jenkins will hang on kubernetes failing to schedule the node due to lack of cpu resources available.

Add cluster size requirement

---

content/getting-started/install-on-cluster.md

When doing `jx create cluster aws` permissions are given to the nodes for uploading to ECR. This has been lacking from this document leading to errors during build like:
`not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr...`
As far as I understand either giving permission or enabling insecure registries are needed, so documenting that.

 Document manually giving nodes ECR permissions 

---

content/commands/jx_create_cluster.md
content/commands/jx_update_cluster.md
content/getting-started/config.md
content/getting-started/config.zh.md

Removed EKS "coming soon" lines.
Changed "AWS or KES (sic)" to just "AWS", as kops clusters on EC2, and EKS are both just "AWS".

EKS no longer "coming soon". Removed spurious "or KES (sic)".

---

content/getting-started/install.md

Hi,
Right now jx installation instructions are not in sync with `jx upgrade cli` - https://jenkins-x.io/getting-started/install/ . `jx upgrade cli` installs upgraded binary in `~/.jx/bin` which may even not be in your PATH. Also `jx upgrade cli` won't (and can't) remove `/usr/local/bin/jx` file, so effectively upgrade is not working.
I propose to improve instructions to copy initial binary straight into `~/.jx/bin` and updating bashrc with the proper PATH entry. With this approach `jx upgrade cli` is gonna work as expected. Plus all the other binary dependencies pulled by jx (like eksctl, helm or kubectl) will be available in the PATH.

Added `jx upgrade cli` friendly installation instructions for Linux

---

content/getting-started/install-on-cluster.md

Some Ingress installations are via DaemonSet and do not have an Ingress service or deployment. In those cases, installing with --skip-ingress --domain may be successful.

Add an installation note about --skip-ingress

---

content/contribute/development.md

Merge the content of jx hacking.md to the contribute to development page of jx-docs.
Related to https://github.com/jenkins-x/jx/issues/1817. Once this PR is approved and merged, I will PR on jx repository to:
- update CONTRIBUTING.MD to simply point to the jenkins-x.io/contribute/development/
- Do the same for hacking.md (or simply delete it... don't know if it would not create dead links)

Merge hacking.md from jx repo into development page

---

content/community.md

It was not obvious to me where I had to signup as I clicked directly on
the room link.  Also given I already has a slack account for a different
workspace trying to add the new workspace was not obvious because
slack.k8s.io is not really a slack workspace, so changed the second URL
to be the workspace URL and not a vanity one.

Use a correct URL to the workspace and add a note about signup.

---

content/demos/talks.md

I have a presentation for an introduction to Jenkins X at the [Korea Developer Conference](http://www.hanbit.co.kr/store/education/edu_view.html?p_code=S8548956082) on 17th November 2018.
I'd like to share it with Jenkins X community.

Add talks: 2018-11-17 Korea Developer Conference at Seoul

---

content/contribute/roadmap.md

The now merged PRs being https://github.com/jenkins-x/jx/pull/2073 for IBM Cloud Private and https://github.com/jenkins-x/jx/pull/1965 for the IBM Cloud Kubernetes Service.

Add IBM Cloud as of 1.3.x

---

content/getting-started/create-custom-builder.md
content/getting-started/create-custom-builder.zh.md

Error this fixes:
```
Error response from daemon: Dockerfile parse error line 9: unknown instruction: CMD["GCC"]
```

fixes custom builder example so docker build succeeds

---

content/contribute/development.md

The code blocks for the testing section are not formatted correctly, which results in some text and shell commands getting displayed incorrectly:
I added a newline after the 3 backticks and marked each block for `shell` syntax highlighting to be consistent with the rest of the page. Here is what it the docs look like with my changes:

Fix formatting of code blocks in testing section of contributing docs

---

content/developing/browsing.md

Fixes 404 on https://jenkins-x.io/developing/browsing/ pointing to https://jenkins-x.io/commands/applications

Fix link for 'jx get applications'

---

config.toml

Resulting in a dedicated jenkins-x.io Google Analytics property (separated from jenkins.io)

Update Google Analytics ID

---

content/faq/issues.md

The create token command is missing `git` as it fails without it.

(docs) Correct the create token command

---

content/getting-started/create-cluster.md

Who is following this guide might find a gcloud login error(like I did) when using `jx create cluster gke` if they were already logged in at gcloud, specially if they followed Google's gcloud tool installation guide that we provided at jx's dependency verification phase. 
This new instruction might help them until there's a specific error handling code about this case.

Update GKE "Connecting to the cluster from your laptop" section

---

content/contribute/development.md

At present 1.11.4 seems to be a known version of golang where go modules behave as expected.

Remove the subtle wording around golang version

---

content/getting-started/config.md

In Getting Started / Configuration page make it clear that ChartMuseum can be overridden by adding a header

Highlight ChartMuseum config with header

---

content/about/accelerate.zh.md
content/about/concepts.zh.md
content/about/features.zh.md
content/about/license.zh.md
content/architecture/_index.zh.md
content/contribute/_index.zh.md
content/contribute/apidocs.zh.md
content/contribute/development.zh.md
content/contribute/documentation.zh.md
content/contribute/roadmap.zh.md
content/contribute/triage.zh.md
content/demos/_index.zh.md
content/developing/_index.zh.md
content/developing/promote.zh.md
content/faq/develop.zh.md
content/faq/faq.zh.md
content/faq/issues.zh.md
content/faq/jenkins.zh.md
content/faq/setup.zh.md
content/faq/technology.zh.md
content/getting-started/_index.zh.md
content/news/_index.zh.md

The aliases where bogus as we had not been generating them for GH Pages
for a long time.  On top of that when we start generating them they
overwrite the English pages as they missed the /zh/ prefix.
Rather than add /zh/ prefix we just remove them as the links would have
been dead for a long time anyway and this is an opertunity to cleanup

remove aliases from Chinese pages

---

content/architecture/components.md

According to  the ChartMuseum(https://chartmuseum.com/) official description  "Host your own Helm Chart Repository" ,so in the context here should be "repository" instead of "registry"

fixed the term "registry" to  the term "repository" in the  4. ChartMuseum

---

content/community/_index.md

Calendar too linked to my work Google account: if my computer sleeps or I switch Google accounts the calendar on the jenkins-x website no longer displays information about office hours.

Edit office hours info

---

content/developing/progressive-delivery.md

it uses the prometheus included with istio
Lock the istio version

fix: prometheus addon is not needed for flagger

---

content/getting-started/aws-terraform-install-gitops.md

Fix AWS IAM Policy for Vault user to get access to KMS key
If you try to use this terraform as is your `vault` containers will never start.
And stuck in a loop with logs like this
```
Error parsing Seal configuration: error fetching AWS KMS sealkey information: AccessDeniedException: User: arn:aws:iam::<account-id>:user/vault_<region-name> is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:<region-name>:<account-id>:key/<key-id>
status code: 400, request id: <id>
```

Fix AWS IAM Policy for Vault user to get access to KMS key

---

content/faq/pipelines.md

I've noticed a wrong redirection, here is the correct one.
/assign @jstrachan
/assign @wbrefvem

Use the correct anchor for differences between JX and Jenkins pipelines

---

content/architecture/custom-jenkins.md

The command that is currently in the documentation gives the following error:
```
could not decode secret: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `NAME   ...` into main.secret
```

fix: Fixing a documentation error with getting password

---

content/getting-started/install.md

Correct jx location and update "sudo mv jx /user/local/bin" to "sudo mv jx /usr/local/bin" for macOS and Linux install instructions under file name: jx-docs/content/getting-started/install.md

fix: update /usr/local/bin

---

content/architecture/components.md

Link redirects to a non existing anchor: https://jenkins-x.io/faq/develop/#How-To-Add-Custom-Annotations-to-Ingress-Controller?

fix: Fix broken link

---

content/getting-started/aws-terraform-install-gitops.md

Update eks.tf example
- 0.12 terraform; 5.0.0 eks module
- remove scale protection so one can destroy autoscaling group

fix: update eks.tf example

---

content/getting-started/install.md

#1761
change original download link from 
`https://github.com/jenkins-x/jx/releases/download/latest/jx-linux-amd64.tar.gz`
to
`https://github.com/jenkins-x/jx/releases/latest/download/jx-linux-amd64.tar.gz`
tested, it works.

fix #1761 linux install link broken

---

content/developing/progressive-delivery.md

After flagger was upgraded in https://github.com/jenkins-x/jenkins-x-versions/pull/325

fix: use the new Flagger metric names

---

content/getting-started/aws-terraform-install-gitops.md

The current Terraform "Getting Started" guide has a syntax error in the Vault IAM policy resource:
```
Error: Missing newline after block definition
```
This is easily fixed by moving the closing brace for the resource to a newline.

docs: fix syntax error in Terraform example

---

content/faq/pipelines.md

There is a weirdly encoded space that causes the markdown to render incorrectly, this change simply replaces it with a regular space. 
src: https://jenkins-x.io/faq/pipelines/

Remove weirdly encoded space that would mess with the markdown rendering

---

content/en/_index.html
content/zh/_index.html

Removed reference to a app.bundle.js which is part of bootstrap, so already included
Removed height on SVG icons on front page; doesn't seem to be needed

Removing console errors

---

content/en/docs/getting-started/_index.md

Signed-off-by: juan131 <juan@bitnami.com>
This PR fixes the link to 'Google Cloud Tutorials' in the 'Getting Started' guide.

fix: Fix broken link in the Getting Started guide

---

content/en/_index.html
content/zh/_index.html

https://jenkins-x.io/docs/contribution-guidelines/
returns
This pull request fixes references to Contribute page and it is pointing to https://jenkins-x.io/docs/contributing/

docs: update link to Contribute page in different language versions

---

docker-compose.yml

The hugo docker image was updated to change "hugo" from an entrypoint to a cmd, to allow other commands to be easily run from the command line; this will take that change into account

fix: add hugo to the server command that starts local hugo

---

content/en/about/_index.md

Currently when clicking on the accelerate link in the about page you get a 404. This PR changes that link to point the accelerate content in the overview section.

fix: Fixes broken link to Accelerate page

---

content/en/about/_index.md

Corrects `Organsiations` to `Organisations`

docs: Fix typo in external link

---

content/en/docs/contributing/documentation/apidocs.md

Page that generate error appear at the URL
https://jenkins-x.io/docs/contributing/documentation/apidocs/
(markdown content/en/docs/contributing/documentation/apidocs.md)

fix: deadlink fix.

---

content/en/docs/reference/components/custom-resources.md

Please consider reading jenkins-x/jx-docs#2120, fixed link appears in
the outdated documentation

fix: temporary fix for /about/features/ link

---

content/en/docs/getting-started/demos-talks-posts/talks.md

Resolves #2132 by removing all talks from the "Getting Started" section for which video recordings could not be found. These talks are already listed in the "Community" section.
I standardized the date format and found some extra video links here and there. The design could perhaps use some help in a future PR.

docs: found new video links, removed unrecorded talks

---

content/en/docs/overview/accelerate.md

fix: add alias for accelerate page on /about/accelerate

---

content/en/docs/concepts/_index.md

Link was pointed to a route that didn't exist. "https://jenkins-x.io/docs/overview/accelerate/" is correct route.

fix: correct link error in issue #2129

---

content/en/docs/managing-jx/faq/issues.md

The example used an invalid casing for the token (`-n GitHub`) which doesn't seem to work in real life.
To avoid confusion with the name `admin`, which can make people guess it is a pre-configured value, I've replaced it with `<yourUserName>`, which is what it should be. This implies - correctly in my assumption - that you have to change this value to your git user name.

chore: improve example for git token 401

---

content/en/community/events/README.md

As a follow-on to Dennis's suggestion in #2148, this adds a readme with the link to Google's rich event docs and two sample events.

docs: add rich events readme

---

content/en/docs/reference/components/vault.md

The ingress configuration example's indenting is not showing correctly. Some parts of the file were incorrectly indented, but for some reason there entire thing is not showing any indenting. So this might not fix it either...

fix: correct ingress example indenting

---

content/es/blog/news/jenkins-x-new-logo.md
content/es/docs/_index.md
content/es/docs/concepts/_index.md
content/es/docs/concepts/jenkins-x-pipelines.md
content/es/docs/contributing/_index.md
content/es/docs/getting-started/_index.md
content/es/docs/getting-started/demos-talks-posts/_index.md
content/es/docs/getting-started/demos-talks-posts/create_cluster_gke.md
content/es/docs/getting-started/demos-talks-posts/create_spring.md
content/es/docs/getting-started/promotion/_index.md
content/es/docs/getting-started/setup/boot/_index.md
content/es/docs/getting-started/setup/create-cluster/_index.md
content/es/docs/getting-started/setup/install/_index.md
content/es/docs/managing-jx/common-tasks/access-control.md
content/es/docs/managing-jx/faq/_index.md
content/es/docs/managing-jx/faq/boot.md
content/es/docs/managing-jx/faq/issues.md

@mmorejon just FYI...it seems Hugo got confused about which page the aliases were pointing to, so some external links that was supposed to link to an english article got the spanish one instead :)

fix: removing aliases from spanish pages to avoid them clashing with the ones for english

---

content/en/docs/getting-started/setup/boot/_index.md

Ideally, we'd be redirecting to the `#ingress` anchor, but I can't
find a way to do that. If anyone has a solution, I'd love to see it. =)
fixes https://github.com/jenkins-x/jx/issues/6192
Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

fix: Add redirect from old TLS URL to boot docs

---

content/en/docs/getting-started/_index.md
content/en/docs/getting-started/setup/install/_index.md
content/en/docs/managing-jx/tutorials/google-hosted.md

Currently, due to a conflict in git versions, the `jx` binary is not compatible with GCP Cloud Shell. Therefore, hiding the instructions, tutorials, and references to using GCP Cloud Shell. 
In the future, when this conflict is fixed, then the tutorials may be helpful again.

docs: hide instructions for Cloud Shell

---

content/en/docs/getting-started/setup/install/_index.md

The command `jx version` cannot be used immediately after installation; it reports `error: unable to load in-cluster configuration`. However, `jx --version` works before the cluster has been set up.

docs: Fix version command in install instructions

---

content/en/docs/getting-started/_index.md
content/en/docs/getting-started/next.md
content/en/docs/getting-started/setup/boot/_index.md
content/en/docs/managing-jx/faq/_index.md

the SaaS would be the simplest way to try out jx, so it makes sense to let people know about it
similarly, the UI should theoretically "just work" for OSS instances, so if people are interested in using it, it'd make sense to make them aware it exists. It's free to use but not OSS

chore: adding references to cloudbees saas + UI

---

content/en/docs/contributing/code/contribute_dns.md
content/en/docs/reference/api.md
content/en/docs/reference/commands/jx_boot.md
content/en/docs/reference/components/vault.md
content/en/docs/using-jx/faq/_index.md
content/es/docs/reference/components/vault.md
content/es/docs/using-jx/faq/_index.md
static/apidocs/index.html

Add note explaining why it must be .yml and not .yaml
Helps explain [#5141](https://github.com/jenkins-x/jx/issues/5141) and clear up confusion with documentation
The requirements loader in the jx cmd code will only load jx-requirements.yml and NOT jx-requirements.yaml. I think that should also be changed to allow for both extensions, however the easy fix right now is to clear up the confusion with the docs first.

fix: Change docs to refer to correct jx-requirements.yml filename

---

content/en/docs/getting-started/setup/install/_index.md
content/es/docs/getting-started/setup/install/_index.md
content/zh/docs/getting-started/setup/install/_index.md

From https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#installing:
> ### Installing
> If it’s on GitHub, users can install any of your formulae with `brew install user/repo/formula`. Homebrew will automatically add your `github.com/user/homebrew-repo` tap before installing the formula. `user/repo/formula` points to the `github.com/user/homebrew-repo/**/formula.rb` file here.
>
> If they want to get your tap without installing any formula at the same time, users can add it with the `brew tap user/repo` command.
Can't tell when that was introduced, but it makes the `brew` installation a one-liner 😁

docs: brew, use one-liner where brew install does it all

---

content/en/docs/reference/multi-cluster.md

**Summary: Yesterday i struggled a lot while installing the environment controller.
In order to save others some time, i'd like to add a small hint to the documentation.**
This was found yesterday in the discussion with @jstrachan and upgrading helm to v2.16.1 did solve the download issue.
The command that raised the issue was:
```
jx create addon envctl -s https://gitlab.server.example.com/environment-production.git --docker-registry gitlab.server.example.com:4567 --cluster-rbac true --user jenkinsx --token XXX --version 0.0.617
```
This led to the error:
```
error: failed to run 'helm fetch -d /tmp/helm-template-workdir-635696494/jxet/chartFiles --untar environment-controller --repo https://storage.googleapis.com/chartmuseum.jenkins-x.io --version 0.0.617' command in directory '', …
```

docs: Update multi-cluster.md: add warning when using older helm version to install the environment controller

---

content/en/docs/getting-started/setup/boot/_index.md
content/en/docs/managing-jx/common-tasks/storage.md

This docs change will include the necessary permissions to write to GCS buckets with a GKE cluster.

feat: Include GKE permissions in boot storage docs

---

content/en/docs/managing-jx/common-tasks/storage.md
content/en/docs/reference/commands/jx_edit_storage.md
content/en/docs/reference/commands/jx_get_storage.md

Previously, I wasn't aware that you could also create new categories with `jx edit storage` as there was no documentation about it, I also improved a few readability related things.

docs: add new categories with jx edit storage

---

content/en/docs/managing-jx/common-tasks/storage.md
content/en/docs/reference/commands/jx_step_stash.md

During testing `jx step stash`  I realized that you have to run `jx step stash` inside the source git repository, otherwise it will always result in a git error.
Since this seems to be very important for now I added it to the docs.

docs: add jx step stash information

---

content/en/docs/getting-started/setup/create-cluster/google.md

Adding a note for users to ensure they've set up a billing account prior to executing `jx create cluster gke`

chore: adding NOTE on setup of billing account.

---

content/en/docs/reference/components/git.md

Some headlines are wrongly indented so that they show up as belonging to the Gitlab section of the page, which they shouldn't.

Correct headline levels in git.md

---

content/en/docs/contributing/code/_index.md

Debugging a boot pipeline with dlv is something we sometimes may want to
do, this commit adds instructions for how to do that with dlv.

feat: Add instructions for debugging jx boot pipeline

---

content/en/docs/reference/commands/deprecation.md

Some of the commands in the deprecation list have been removed from Jenkins-X and are no longer in there.
fixes #2628

chore: update deprecation list

---

content/en/docs/getting-started/setup/create-cluster/eks.md

Receive an error when running terraform apply when output is inside of module. Moved it outside of the module block.

fix: move output outside of module

---

assets/scss/_styles_project.scss

The Bootstrap theme brings colorful alerts, but the links within alerts were not being displayed correctly or were invisible.  Fixes #2685 Closes #2685

fix: link color within bootstrap alerts

---

content/en/docs/labs/boot/_index.md
content/en/docs/labs/boot/apps.md
content/en/docs/labs/boot/background.md
content/en/docs/labs/boot/benefits.md
content/en/docs/labs/boot/comparison.md
content/en/docs/labs/boot/faq/_index.md
content/en/docs/labs/boot/getting-started/_index.md
content/en/docs/labs/boot/getting-started/cloud/_index.md
content/en/docs/labs/boot/getting-started/cloud/gcloud.md
content/en/docs/labs/boot/getting-started/cloud/terraform.md
content/en/docs/labs/boot/getting-started/config.md
content/en/docs/labs/boot/getting-started/repository.md
content/en/docs/labs/boot/getting-started/run.md
content/en/docs/labs/boot/getting-started/secrets/_index.md
content/en/docs/labs/boot/getting-started/secrets/vault.md
content/en/docs/labs/boot/how-it-works.md
content/en/docs/labs/boot/multi-cluster.md
content/en/docs/labs/boot/progressive-delivery.md
content/en/docs/labs/jenkins/_index.md
content/en/docs/labs/jenkins/getting-started.md
content/en/docs/labs/jenkins/importing.md
content/en/docs/labs/jenkins/overview.md
content/en/docs/labs/jxl.md
content/en/docs/labs/wizard/_index.md
content/en/docs/labs/wizard/jenkins.md
content/en/docs/labs/wizard/overview.md

This PR adds the warning from the initial labs page to all the labs pages. That way, people will know that it is experimental and that the current labs are closed no matter whether they navigate through the left-hand navigation, or stumble upon one of the pages through, let's say, Google search.

chore: adding labs warning to all labs related documentation

---

jenkins-x.yml

Will ensure the sitemap entries contain full URLs
fixes #2763

fix: making sure base URL for the release site is set to https://jenkins-x.io

---

content/en/docs/guides/using-jx/faq/_index.md

The docs should not take such an aggressive view of monorepos and should focus only on what users need to do differently if they're using them.

fix: Softening monorepo language

---

docker-compose.yml

Fixes #2790 
Problem arises from using double quotes in [docker-compose.yml](https://github.com/jenkins-x/jx-docs/blob/master/docker-compose.yml) file.
The line causing the issue is: 
```    
command: "htmlproofer ./public --allow-hash-href --disable-external --check-html --checks-to-ignore ScriptCheck --empty-alt-ignore --file-ignore /.*apidocs.*/,/.*\/zh.*/,/.*\/es.*/,/.*\/docs\/reference\/api.*/,/.*\/docs\/reference\/config.*/,/.*\/community\/events.*/"
```
To check the configuration of the YAML file visit http://www.yamllint.com/ 
Using single quotes instead of double quotes.

fix: Parsing yaml file

---

content/en/community/documentation/_index.md

Found and fixed a spelling error in the community documentation.

fix: Typo in community documentation

---

content/en/docs/guides/using-jx/creating/import.md

Fixes https://github.com/jenkins-x/jx/issues/7098

docs: Add a notice/doc to warn about not puting a config.json at the root folder

---

content/en/docs/reference/multi-cluster.md

Removing the `jxl` reference for a multi-cluster solution.  That will arrive upstream sometime in the future.  Closes #2810

docs: remove reference to jxl experimental info

---

content/en/docs/getting-started/_index.html

The /docs direct went missing, causing a 404 on a common page URL. Restoring the alias here.

fix: restoring /docs redirect

---

content/en/blog/news/provision-jx-clusters-terraform.md

The instructions on this post are not relevant given that we now have the Terraform modules published.

docs: unpublishing old blog post

---

content/en/blog/news/lighthouse-goes-ga.md

I'd appreciate any feedback. =)

chore: Lighthouse Goes GA blog post

---

layouts/partials/navbar.html
layouts/partials/scripts.html

- Removed Google Analytics
- Added Google Tag Manager
Both were in the <head>. Google Tag Manager is a faster, more flexible method of pushing tags like Google Analytics on the web.

docs: removed Google Analytics and replaced it with Google Tag Manager

---

content/en/docs/install-setup/installing/create-cluster/eks.md

Configuring Vault for EKS link redirected to 404. I have added the correct link pointing to https://jenkins-x.io/docs/install-setup/installing/boot/clouds/amazon/#configuring-vault-for-eks

fix: Added correct link for Vault for EKS

---

content/en/docs/install-setup/installing/boot/git-provider.md

Changing Git to SCM because it's what more people are likely to search for and parse the page for.

fix: changing git to SCM

---

Makefile
assets/scss/_code.scss
assets/scss/_styles_project.scss
assets/scss/_variables_project.scss
config.toml
content/en/community/documentation/reference.md
content/en/docs/install-setup/create-cluster/eks.md
content/en/docs/install-setup/create-cluster/gke.md
content/en/docs/labs/boot/getting-started/cloud/gcloud.md
docker-compose.yml
jenkins-x.yml
layouts/partials/scripts.html

fix: remove highlightjs and use chroma

---

content/en/about/concepts/features.md

The link to install Jenkins X, if the description is correct, should probably point to the "boot" setup instructions rather than the cli install instructions. Perhaps there's a better place to link than what I'm suggesting, but the existing link is just confusing.

fix: #2982 correct the "install Jenkins X" link

---

content/en/docs/reference/pipeline-syntax-reference.md

Update the pipeline syntax reference to add the tekton `sidecars`
See https://github.com/jenkins-x/jx/issues/7488
Related jx PR: https://github.com/jenkins-x/jx/pull/7489
Note: don't merge before https://github.com/jenkins-x/jx/pull/7489 has been merged

feat(pipelines): document new support for Tekton Sidecar containers

---

content/en/docs/v3/guides/infra/minikube.md

When trying to use Docker with minikube, I got this notification after minikube create the cluster:
```
Due to networking limitations of driver docker on darwin, ingress addon is not supported.
Alternatively to use this addon you can use a vm-based driver:
'minikube start --vm=true'
To track the update on this work in progress feature please check:
https://github.com/kubernetes/minikube/issues/7332
```

fix: tell minikube to use VM

---

content/en/docs/build-test-preview/jenkins-x-pipelines/_index.md

Documentation incorrectly said the pipeline file in a build pack is named `jenkins-x.yml` but it's `pipeline.yaml`.

fix: build pack pipeline file name

---

content/en/docs/v3/guides/upgrade.md

Or maybe, we just replace this strategy here: https://github.com/jenkins-x/jx-gitops/blob/5194dc6e8628be69d56abf09cff86f47adacb979/pkg/cmd/kpt/update/update.go#L251
with `resource-merge`, unless @rawlingsj has a really good reason for doing this :p

docs: how to change strategy for jx gitops upgarde

---

config.toml

Expand sidebar menu by default in order to see directly where to look for a particular section instead of having to click on each of them
) in the commit message and PR title for the semantic checks to pass.

fix(menu): expand sidebar menu by default

---

content/en/v3/admin/guides/tls_dns.md

docs: fix TLS docs after switching nginx to use a default cert

---

config.toml

Expand only "About" menu section when opening v3 doc

fix: Expand only "About" menu section when opening v3 doc

---

content/en/v3/about/how-it-works.md

I'm pretty sure that the file has moved from `.jx/` to `versionStream/` in v3.
incorrect docs
- [NA] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [NA] Any dependent changes have already been merged.

docs: invalid path to .../git-operator/job.yaml

---

content/en/v3/admin/guides/migrate/v2.md

Add missing 'jx gitops repository export' doc link

fix(migration): add missing 'jx gitops repository export' doc link

---

content/en/v3/about/overview/_index.md

Update link for `kubernetes-external-secrets`
- Before: https://github.com/godaddy/kubernetes-external-secrets
- After: https://github.com/external-secrets/kubernetes-external-secrets
Someone will also need to update the [diagram on whimsical](https://whimsical.com/embed/SnJBgXG6jz9pqQewiDTNRt@2Ux7TurymNDXVRa4FpLk).

chore: update link for kubernetes-external-secrets

---

config.toml

we have lots of documentation sections so auto-expanding all the docs is confusing

fix: use compact menu by default

---

content/en/v3/admin/setup/operator/_index.md

fix: Remove delete_repo as pre-populated GitHub PAT token permissions as it seems not to be in use.
Signed-off-by: Elias Abacioglu elias.rabi@gmail.com
It's not smart to ask for more permissions than what is needed from a security perspective.
Remove delete_repo as pre-populated GitHub PAT token permissions as it seems not to be in use.

fix: Install operator: remove delete_repo permission

---

content/en/_index.html
content/en/docs/reference/components/source.md
content/en/v3/about/changes.md
content/en/v3/about/extending.md
content/en/v3/admin/setup/upgrades/cli.md
content/en/v3/devops/patterns/push_version_changes.md

chore: fix old jx-cli links

---

content/en/v3/admin/platforms/minikube/_index.md
content/en/v3/admin/platforms/on-premise/_index.md
content/en/v3/admin/platforms/openshift/_index.md

The default branch name for the following template repository is `main`, 
-  [jx3-gitops-repositories/jx3-minikube](https://github.com/jx3-gitops-repositories/jx3-minikube/generate)
- [jx3-gitops-repositories/jx3-kubernetes](https://github.com/jx3-gitops-repositories/jx3-kubernetes/generate)
- [jx3-gitops-repositories/jx3-openshift](https://github.com/jx3-gitops-repositories/jx3-openshift/generate)
However, the commands listed in Getting Started assume a `master` branch.
```
git push origin master
```
Therefore, we have modified the command to assume the `main` branch.
```
git push origin main
```
Fixes #3309

docs: fix git command because default GitHub branch name is 'main'.

---

content/en/v3/admin/guides/multi-cluster/multi-cluster.md

The url for this section has changed but the link was not updated.

fix: update links to why-does-jenkins-x-use-helmfile-template

---

content/en/community/_index.md
content/en/community/office_hours/_index.md
content/es/community/_index.md

the old zoom link was still present in a few place, let's remove it for real this time!

fix: remove old zoom link for office hours

---

content/en/blog/news/2020-jx-v3-beta.md
content/en/blog/news/2020-jx-v3.md
content/en/blog/news/2021-jx-v3-ga.md
content/en/docs/install-setup/boot/clouds/_index.md
content/en/docs/install-setup/boot/clouds/on-premises.md
content/en/docs/resources/faq/setup.md
content/en/docs/resources/guides/managing-jx/old/install-on-cluster.md
content/en/v3/admin/platforms/on-premises/_index.md
content/en/v3/admin/platforms/on-premises/vault.md
content/en/v3/admin/platforms/on-premises/webhooks.md
content/en/v3/admin/setup/config/storage.md
content/en/v3/admin/setup/ingress/default.md
content/en/v3/admin/setup/operator/_index.md
content/en/v3/admin/setup/secrets/vault.md
content/en/v3/admin/setup/upgrades/migrations.md
content/en/v3/admin/troubleshooting/webhooks.md
content/en/v3/develop/faq/config/ingress.md
content/en/v3/develop/reference/jx/gitops/webhook/update/_index.md
content/zh/v3/admin/troubleshooting/webhooks.md
layouts/shortcodes/admincards.html

A _premise_ is "[a proposition […] supposed or proved as a basis of argument or inference](https://www.merriam-webster.com/dictionary/premise)", while _premises_ refers to "[a tract of land with the buildings thereon](https://www.merriam-webster.com/dictionary/premises)".
See also: [re:Invent 2018 premises/premise supercut](https://www.youtube.com/watch?v=RWHocP0AzMc)

Fix usage of "on-premises"

---

content/en/v3/admin/guides/preview-environments/_index.md

the release name is mandatory, so let's make sure that people following this admin guide will end up with a valid helmfile.yaml

fix: ensure the osiris helmfile is valid

---

content/en/v3/develop/faq/issues.md

Fixes a typo in the issues.md file, where the title is "Troublehshooting" instead of "Troubleshooting".

docs: Fix typo in title of Troubleshooting page

---

content/en/v3/admin/guides/lighthouse-webui/_index.md

ensure we use the new chart prefix `jxgh`, instead of the old one `jx3`

fix: v3 admin guide for lighthouse-webui

---

content/en/v3/admin/platforms/minikube/_index.md

Without virtualbox, `minikube --vm=true` fails.

docs: add virtualbox prerequisite

---

content/en/v3/admin/guides/lighthouse-webui/_index.md

ori failed with 
```
error: failed to process helmfile helmfiles/jx/helmfile.yaml: failed to resolve helmfile {helmfiles/jx/helmfile.yaml ../../}: failed to match prefix jx3 with repositories from versionstream : no matching repository for for prefix jx3
make[1]: *** [versionStream/src/Makefile.mk:114: fetch] Error 1
make[1]: Leaving directory '/workspace/source'
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:241: regen-check] Error 1
```

Fix broken config

---

.lighthouse/jenkins-x/preview.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
README.md
docker-compose.yml

* https://gohugo.io/getting-started/installing/#docker -> Hugo installation website recommends using `klakegg/hugo`. 
Our custom image is basically the same image, with a different name and tag: https://github.com/jenkins-x/hugo-extended-docker/blob/master/Dockerfile
* Also updates the docsy submodule.

refactor: move to official hugo docker images

---

content/en/community/_index.md
content/zh/docs/contributing/code/_index.md

Discourse was taken down as mentioned in https://github.com/jenkins-x/jx-docs/issues/3473#issuecomment-955192189
Fixes #3473.

fix: remove references to Discourse (fixes #3473)

---

content/en/community/code/_index.md

I was confused about what types and scopes can I use for `hacktoberfest` commits, and although it is over, I thought it might be worthy to document it in a less abstract way.
Fixes #3474.

fix: clarify commit types and scopes (#3474)

---

content/en/v3/admin/platforms/eks/_index.md
content/en/v3/develop/ui/slack.md

For end users who dont use vault, but use aws secrets manager, we dont have any mention of the jx3-eks-asm template repo which should be used as a starting point for creating the cluster git repo.

fix: add links to jx3-eks-asm template

---

.gitmodules

fix: use shallow clone for submodules

---

content/en/v3/admin/setup/secrets/vault.md

add instructions how-to proxy jx-secret traffic through the cluster.  This allows users to use the `jx secret` command locally, while the traffic and vault access is taken care of by the cluster.

fix (external-vault): instructions how-to proxy jx-secret to external vault

---

content/en/v3/admin/setup/jx3/_index.md

fix: Typo in help command

---

content/en/v3/admin/setup/upgrades/cli.md

Sometimes there are deprecated plugins locally, then `jx upgrade plugins` errors out.

fix: small note on deprecated plugins

---

content/en/v3/admin/uninstall/_index.md
content/en/v3/admin/uninstall/delete-jx-cluster.md
content/en/v3/admin/uninstall/delete-jx.md

Webhooks are not deleted automatically when Jenkins X is uninstalled.

refactor: add a note about manually deleting webhooks from repositories

---

content/en/v3/admin/platforms/eks/_index.md

Removed the requirement to setup ECR in advance. 
Added some more info on procedure for setting the Bot token.
Fixed some links

docs: going through the install procedure - AWS Vault

---

content/en/v3/admin/setup/operator/_index.md
content/en/v3/develop/reference/jx/admin/operator/_index.md

Fixes # git config --global http.sslverify -> sslVerify / see https://git-scm.com/docs/git-config
- [ x] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ x] Any dependent changes have already been merged.

Fixed git config http.sslVerify typo

---

config.toml

The new icons added aren't showing on routes other than "/"

fix: new icons in /community route

---

content/en/v3/develop/apps/_index.md
content/en/v3/develop/create-project/_index.md
content/en/v3/develop/pipelines/_index.md

Fixing broken links in docs
Fixes [#8043](https://github.com/jenkins-x/jx/issues/8043)

fix: broken links in docs

---

content/en/v3/develop/create-project/_index.md

Quickstart link was pointing to v2. Changed it to v3. Also added the troubleshooting link.

fix: add the link to quickstart documentation and troubleshooting

---

.lighthouse/jenkins-x/pullrequest.yaml
content/en/_index.html
content/en/blog/news/2021-jx3-builtin-observability.md

A tweet we use in a blog was removed, so twitter returned an error. 
Let's not use `ignoreErrors = ["error-remote-getjson"]` to ignore the these kind of errors (always better to remove things that dont work instead of ignoring them).
Also tweet shortcode now requires an user and id, fixing that also

fix: remove link to deleted tweet and add user and id to tweet shortcode

---

content/en/v3/admin/platforms/k3s/_index.md

After trying to install Jenkins-x with the k3s approach I came across some problems that may be solved by changing commands in the documentation
1) Explaining how to export the needed env variables permanently in the .bashrc file as you will be required to open multiple terminals
2) Copying the Configuration of the `/etc/rancher/k3s/k3s.yaml` to the `./kube/config` and changing the permissions if needed
3) Remainder to use v1.21 if installing k3s from their installation guide
4) Add docker installation and post-installation link from the official documentation
5) Add the step of installing the jx 3 binaries from the docs before running the jx admin operator command
6) If the jx secrets weren't generated, make a direct push through the GitHub repository itself, not the `git push` command …

docs: Edit the  v3 / admin / platforms / k3s  documentation

---

content/en/v3/admin/platforms/eks/_index.md

For the documentation on how to set up [Jenkins x on Amazon](https://jenkins-x.io/v3/admin/platforms/eks/)
Wrapping every commands block into bash block 
altering the link to create or import projects to refer to the website
I think this was looking fine on the _index.md in GitHub but the website now looks like this :

docs: wrapping commands in a bash block

---

go.mod
go.sum

Suddenly builds started failing due to docsy as a go module.
This PR fixes breaking release builds due to docsy package naming scheme changes.

fix: remove v tag from docsy package name

---

content/en/v3/admin/platforms/minikube/_index.md

Jenkins X is currently only runnning on no version later than 1.21 of kubernetes, that needs to be set as argument to minikube

fix: Minikube set kubernetes version

---

content/en/v3/develop/faq/using.md

Signed-off-by: rajatgupta24 <rajat2411gupta@gmail.com>
Better explanation on how to store git credential

fix: add information around git credential store

---

content/en/v3/admin/platforms/k3s/_index.md

It's possible to run multiple named tunnels using ngrok for unlimited time. 

fix: add docs around multiple named ngrok tunnels

---

content/en/v3/admin/platforms/k3s/_index.md

We made a change to the documentation to forward multiple ports using named tunnels in ngrok.
But no changes were made to point out which forwarding ip/url should be used for the hook service.

fix: make it clear which ngrok forwarding url to use for hook service

---

content/en/v3/develop/faq/using.md

if XDG_CONFIG_HOME is not set to `$HOME`, then git will not read the credentials found in the ~/git/credentials
and instead search for credentials in the ~/.git-credential file.

fix: set XDG_CONFIG_HOME to `$HOME` to use credentials in git/credentials

---

.github/workflows/regenerate.yml

Regeneration of plugin docs have not worked in a while due to the addition of a branch protection rule.
This is an attempt of fixing that by creating pull request to be merged by lighthouse.
It's not possible to give Github Actions permissions to psu to a protected branch as far as I understand this: https://github.com/orgs/community/discussions/25305

fix: Make regeneration of plugin docs work again

---

Makefile
content/en/community/documentation/_index.md

This PR changes the docker-compose to docker compose.
**_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._**
This PR does not add any new dependency.
Fixes #3654

fix: changing docker-compose to docker compose in makefile

---

content/en/community/_index.md

This PR adds jx-community link.

fix: add jx-community repo link

---

.lighthouse/jenkins-x/preview.yaml
charts/preview/templates/ingress.yaml

doc PRs are failing because of 
```
fatal: unsafe repository ('/workspace/source' is owned by someone else)
--
  |   |   |   | To add an exception for this directory, call:
  |   |   |   |  
  |   |   |   | git config --global --add safe.directory /workspace/source
```
Ideally this should should be added in git clone step though!

ci: fix jx preview prs

---

content/en/v3/admin/platforms/k3s/_index.md

I was following the k3s guide and the k3s by default install 1.25, which is not support by **jx** yet.
So, we should add the version tag which installs 1.24.

fix: add version tag to k3s install command

---

content/en/v3/admin/setup/config/repository.md

- typo in `snapshotURL` corrected as per [MavenRepositoryConfig](https://github.com/jenkins-x/jx-api/blob/master/docs/config.md#mavenrepositoryconfig)

fix: snapshotURL corrected to snapshotUrl

---

content/en/v3/develop/ui/lens.md

Add a simple alert that Lens v6 is not supported
Fixes #3664

chore: add alert that Lens v6 is not supported

---

content/en/blog/news/2021-debug-tekton.md
content/en/v3/develop/pipelines/debugging.md

Adds simple alert that breakpoint used by jx-lens no longer functions
Fixes # 3694

chore: add alerts that breakpoint used by jx-lens no longer function

---

content/en/v3/admin/setup/operator/_index.md

It was a bit confusing without conventional documentation placeholders. As a new user, I thought the process was creating a new separate service/user. This update to use more conventional placeholders makes it clearer that the user should insert their existing GitHub username.
- [x ] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [x ] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).

refactor: updates to use conventional placeholders for username reference

---

content/en/v3/admin/setup/jx3/_index.md

jenkins-x/homebrew-jx is the homebrew repo for installing the jx client for Jenkins X

Include Homebrew

---

.github/ISSUE_TEMPLATE/config.yml

* fixes issue https://github.com/jenkins-x/jx-docs/issues/3717
Signed-off-by: CJ Steiner <clintonsteiner@gmail.com>
- [ X] I have mentioned the appropriate type(scope), as referenced [here](https://jenkins-x.io/community/code/#the-commit-message) in the commit message and PR title for the semantic checks to pass.
- [ X] I have signed off the commit, as per instructions mentioned [here](https://jenkins-x.io/community/code/#how-to-sign-your-commits).
- [ X] Any dependent changes have already been merged.

fix: remove broken reference to discourse page

---

content/en/v3/admin/platforms/eks/_index.md

To simplify the module the terraform-aws-eks-jx module it doesn't run `aws eks update-kubeconfig` any more

add instruction regarding connect to eks
